DROP TABLE IF EXISTS spotify;
CREATE TABLE spotify(
	id VARCHAR (30) NOT NULL,
	title VARCHAR NOT NULL,
	artist VARCHAR(30) NOT NULL,
	top_genre VARCHAR(30) NOT NULL,
	year INT NOT NULL,
	bpm INT NOT NULL,
	nrgy INT NOT NULL,
	dnce INT NOT NULL,
	dB INT NOT NULL,
	live INT NOT NULL,
	val INT NOT NULL,
	dur INT NOT NULL,
	acous INT NOT NULL,
	spch INT NOT NULL,
	pop INT NOT NULL
	);
	